### ISSUE TITLE
Nix shell? Seriously?

### ISSUE THREAD

**Issue by c4eater** [pSub/pepper-and-carrot-pdfs#17]
Guys why not write the deployment script using a slightly less exotic scripting language?

**Comment by pSub** [comment]
The script is not written in the Nix language. The only job of `nix-shell` in this script is to ensure that the tools jq, curl, imagemagick, ghostscript, file and zsh are present. Everything else is more or less POSIX compliant.

Anyhow, this is a little, personal project. For such, it makes sense to use the tools you are familiar with. Don't you think?
