### ISSUE TITLE
Some PDFs in English Folder are German

### ISSUE THREAD

**Issue by Vrroom** [pSub/pepper-and-carrot-pdfs#19]
Thanks for doing this!

I think some of the documents in the `en` folder are actually in German. I think these are Episode 29/30 onward.

**Comment by pSub** [comment]
You're right. It seems that episodes 29 - 33 are in German. I'll push a fix later. 

Thank you for reporting this! :heart:

**Comment by pSub** [comment]
Should be fixed now. :rocket: 

Thank you again for the report! Much appreciated. :two_hearts:
